#!/usr/bin/env python3

import pathlib
import re
import sys
from datetime import timedelta
from xml.etree import ElementTree as ET


# parse correct start and end times
def parse_time_expression(expression, default_offset=timedelta(0)):
    offset_time = re.match(r'^([0-9]+(\.[0-9]+)?)(h|m|s|ms|f|t)$', expression)
    if offset_time:
        time_value, fraction, metric = offset_time.groups()
        time_value = float(time_value)
        if metric == 'h':
            return default_offset + timedelta(hours=time_value)
        elif metric == 'm':
            return default_offset + timedelta(minutes=time_value)
        elif metric == 's':
            return default_offset + timedelta(seconds=time_value)
        elif metric == 'ms':
            return default_offset + timedelta(milliseconds=time_value)
        elif metric == 'f':
            raise NotImplementedError('Parsing time expressions by frame is not supported!')
        elif metric == 't':
            if tick_rate is None:
                raise NotImplementedError('Time expression contains ticks but tickRate is not specified!')
            return default_offset + timedelta(seconds=time_value/tick_rate)


    clock_time = re.match(r'^([0-9]{2,}):([0-9]{2,}):([0-9]{2,}(\.[0-9]+)?)$', expression)
    if clock_time:
        hours, minutes, seconds, fraction = clock_time.groups()
        return timedelta(hours=int(hours), minutes=int(minutes), seconds=float(seconds))

    clock_time_frames = re.match(r'^([0-9]{2,}):([0-9]{2,}):([0-9]{2,}):([0-9]{2,}(\.[0-9]+)?)$', expression)
    if clock_time_frames:
        raise NotImplementedError('Parsing time expressions by frame is not supported!')

    try:
        return timedelta(seconds=float(expression))   # As found in auto-generated YouTube TTML
    except ValueError:
        pass

    raise ValueError('unknown time expression: %s' % expression)

def parse_times(elem, default_begin=timedelta(0)):
    if 'begin' in elem.attrib:
        begin = parse_time_expression(elem.attrib['begin'], default_offset=default_begin)
    elif 'start' in elem.attrib:
        begin = parse_time_expression(elem.attrib['start'], default_offset=default_begin)
    else:
        begin = default_begin
    elem.attrib['{abs}begin'] = begin

    end = None
    if 'end' in elem.attrib:
        end = parse_time_expression(elem.attrib['end'], default_offset=default_begin)

    dur = None
    if 'dur' in elem.attrib:
        dur = parse_time_expression(elem.attrib['dur'])

    if dur is not None:
        if end is None:
            end = begin + dur
        else:
            end = min(end, begin + dur)

    elem.attrib['{abs}end'] = end

    for child in elem:
        parse_times(child, default_begin=begin)


LEADING_WHITESPACE = re.compile(r"^\s+")
TRAILING_WHITESPACE = re.compile(r"\s+$")

NEWLINE_WITH_TRAILING_SPACE = re.compile(r"\n\s+")
NEWLINE_WITH_LEADING_SPACE = re.compile(r"\s+\n")

FONT_OR_I_1 = re.compile(r'(?P<all>(\s|^)<(font color="([^"]+)"|i)>) +')
FONT_OR_I_2 = re.compile(r' +(?P<all></(font|i)>(\s|$))')
MULTI_COLOR_FONT = re.compile(
    r'<font color="(?P<color1>[^"]+)">(?P<startspaces>\s*)<font color="(?P<color2>[^"]+)">(?P<text>[^<]+)</font>(?P<endspaces>\s*)</font>'
)

CLOSING_TAG = re.compile(r'\n+(?P<all></(font|i)>)')
FONT_COLOR = re.compile(r'<font color="([^"]+)">(?P<spaces>\s*)</font>')

TRIPLE_NEWLINE = re.compile(r"\n\n\n+")


# render subtitles on each timestamp
def render_subtitles(elem, timestamp, styles):
    if timestamp < elem.attrib['{abs}begin']:
        return ''
    if elem.attrib['{abs}end'] is not None and timestamp >= elem.attrib['{abs}end']:
        return ''

    result = []

    style = {}
    if 'style' in elem.attrib:
        # Handle multiple entries in the 'style' attribute,
        # e.g.
        #
        #   <elem style="autogenFontStyle_n_150_120 S1 StyleFillLineGapTrue">
        #
        for s in elem.attrib["style"].split():
            style.update(styles[s])

    if 'color' in elem.attrib:
        style['color'] = elem.attrib['color']

    if 'fontStyle' in elem.attrib:
        style['fontstyle'] = elem.attrib['fontStyle']

    if 'color' in style:
        result.append('<font color="%s">' % style['color'])

    if style.get('fontstyle') == 'italic':
        result.append('<i>')

    if elem.text:
        result.append(TRAILING_WHITESPACE.sub(' ', LEADING_WHITESPACE.sub(' ', elem.text)))

    for child in elem:
        result.append(render_subtitles(child, timestamp=timestamp, styles=styles))
        if child.tail:
            result.append(TRAILING_WHITESPACE.sub(' ', LEADING_WHITESPACE.sub(' ', child.tail)))

    if 'color' in style:
        result.append('</font>')

    if style.get('fontstyle') == 'italic':
        result.append('</i>')

    result = ''.join(result)

    result = FONT_OR_I_1.sub('\g<all>', result)
    result = FONT_OR_I_2.sub('\g<all>', result)
    result = NEWLINE_WITH_TRAILING_SPACE.sub('\n', result)
    result = NEWLINE_WITH_LEADING_SPACE.sub('\n', result)

    result = MULTI_COLOR_FONT.sub(
        r'\g<startspaces><font color="\g<color2>">\g<text></font>\g<endspaces>',
        result
    )

    result = CLOSING_TAG.sub('\g<all>\n', result)

    result = FONT_COLOR.sub('\g<spaces>', result)

    if elem.tag in {'div', 'p', 'br'}:
        result += '\n'

    return result


def format_timestamp(timestamp: timedelta):
    return ('%02d:%02d:%06.3f' % (timestamp.total_seconds()//3600,
                                  timestamp.total_seconds()//60%60,
                                  timestamp.total_seconds()%60)).replace('.', ',')


def convert_ttml_to_srt(ttml_subtitles):
    root = ET.fromstring(ttml_subtitles)

    # strip namespaces
    for elem in root.iter():
        elem.tag = elem.tag.split('}', 1)[-1]
        elem.attrib = {name.split('}', 1)[-1]: value for name, value in elem.attrib.items()}

    tick_rate = root.attrib.get('tickRate', None)
    if tick_rate is not None:
        tick_rate = int(tick_rate)

    # get styles
    styles = {}
    for elem in root.findall('./head/styling/style'):
        style = {}
        if 'color' in elem.attrib:
            color = elem.attrib['color']
            if color not in {'#FFFFFF', '#000000'}:
                style['color'] = color
        if 'fontStyle' in elem.attrib:
            fontstyle = elem.attrib['fontStyle']
            if fontstyle == 'italic':
                style['fontstyle'] = fontstyle
        styles[elem.attrib['id']] = style

    body = root.find('./body')
    if not body and root.tag == 'transcript':
        body = root  # Tolerate YouTube auto-generated TTML

    parse_times(body)

    timestamps = set()
    for elem in body.findall('.//*[@{abs}begin]'):
        timestamps.add(elem.attrib['{abs}begin'])

    for elem in body.findall('.//*[@{abs}end]'):
        timestamps.add(elem.attrib['{abs}end'])

    timestamps.discard(None)

    rendered = []
    for timestamp in sorted(timestamps):
        rendered.append((
            timestamp,
            TRIPLE_NEWLINE.sub('\n\n', render_subtitles(body, timestamp=timestamp, styles=styles)).strip()
        ))

    if not rendered:
        exit(0)

    # group timestamps together if nothing changes
    rendered_grouped = []
    last_text = None
    for timestamp, content in rendered:
        if content != last_text:
            rendered_grouped.append((timestamp, content))
        last_text = content

    # output srt
    rendered_grouped.append((rendered_grouped[-1][0]+timedelta(hours=24), ''))

    lines = []

    srt_i = 1
    for i, (timestamp, content) in enumerate(rendered_grouped[:-1]):
        if content == '':
            continue
        lines.append(str(srt_i))
        lines.append(format_timestamp(timestamp)+' --> '+format_timestamp(rendered_grouped[i+1][0]))
        lines.append(content)
        srt_i += 1
        lines.append('')

    return "\n".join(lines)


if __name__ == '__main__':
    for path in sys.argv[1:]:
        ttml_file = pathlib.Path(path)

        if ttml_file.suffix != ".ttml":
            sys.exit(f"Expected ttml file as input, got {path}")

        ttml_subtitles = ttml_file.read_text()
        srt_subtitles = convert_ttml_to_srt(ttml_subtitles)

        srt_file = ttml_file.with_suffix(".srt")
        srt_file.write_text(srt_subtitles)
        print(srt_file)
